
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pod
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
<<<<<<< HEAD
      path: /mutate-apps-openkube-com-v1beta1-unitedset
=======
      path: /mutate-apps-openKube-com-v1beta1-unitedset
>>>>>>> 3df08e30ce418fc56f172b30f18b0bb3094557fc
  failurePolicy: Fail
  name: munitedset.kb.io
  rules:
  - apiGroups:
    - apps.openKube.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - unitedsets

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
<<<<<<< HEAD
      path: /validate-apps-openkube-com-v1beta1-unitedset
=======
      path: /validate-apps-openKube-com-v1beta1-unitedset
>>>>>>> 3df08e30ce418fc56f172b30f18b0bb3094557fc
  failurePolicy: Fail
  name: vunitedset.kb.io
  rules:
  - apiGroups:
    - apps.openKube.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - unitedsets
