# permissions for end users to edit unitedsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unitedset-editor-role
rules:
- apiGroups:
  - apps.openkube.com
  resources:
  - unitedsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openkube.com
  resources:
  - unitedsets/status
  verbs:
  - get
