apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: openkube-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3hNekF5TURBMU4xb1hEVE13TURjeE1UQXlNREExTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEZRCkhlbDd1SW4vVGVGbmFHRVlvOElOQWlZeEFrbmF1UnY2TGhYVXYwV25lRHFONVJ1M0FoRzM5ZlJvSFhzQURRUWIKWWRXRmtjU1FJUGNzWmdJMy9nNFdGVkhvd2s3Rk5qdUlWdzBDc0dsS05XZldkeG9NV0Y4YkNsVEpoRU9Td3ZkbQprU1NYdllpdzlkVVhDa3kweXgvdzE2WkN4ZXBPUzJsTUFqc3ZjenhWd3dZbUZ4RDBQUEdrbkIwOUdNUjVXNzdPCjVQdFhRMUo2T1pNcmVLdDB0YllOZ25LTHdqSk5GZVFxZzZCR2ZYQVFwUkhNUHpIdHlNV3MxWkg2TTQwZ0FoVEgKQjkwbzJ1QWQwRXpWM1p0YWp3dnBHSmN0UFJvQXNmYWpjTDRqOFU5MUlpTmMyLzRtK3RQZ0lCVUJZT0ZJWDBWbApQVG8yMU1tcWdBSXREeGNJRDZjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFPclFRMXZoMlk0WE5mWC9BWEluNEtuVlArdVIKaW15Y0dQdmJiZTJqYXZOVHRGMGJ5Ui9QdGxNNDlzSmxZWEhwSStyYmZxYzd3SGx5RTdmVFA3TWRseTJFTDVTUwpCQW94d3p6eVUzeFpBTUptbHRGWitWMDZ4Zi94aE1TY2FvTW5EQ0Q2TmdBbmZvMkNmRGxaR2NHeXJNNUVZeDFICkg5dXpNWmxTc3NSQTE4Y1c3UlNZYW9oazhHenZJc2grUitKd1l5bnoxZTBzOXVZYzFEM20xbWl4dFpsY2dGNjAKOW5leFlVQlBqVlIxc1ZLZGxsdmcxclRHZHdTQ3ZaV28vL1NBS0RmWEZHRnFoM3QyWEVzcUNWY3pkWVozMFdpVQpQMGdNbnBzWW8yUmpGbHN6SitoUUVRNlBQei9HZHQ4RlEwODlzTTBtM2ZWdnRMRXc3NVpzczgrRUphdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: openkube-webhook-service
      namespace: openkube-system
      path: /mutate-pod
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3hNekF5TURBMU4xb1hEVE13TURjeE1UQXlNREExTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEZRCkhlbDd1SW4vVGVGbmFHRVlvOElOQWlZeEFrbmF1UnY2TGhYVXYwV25lRHFONVJ1M0FoRzM5ZlJvSFhzQURRUWIKWWRXRmtjU1FJUGNzWmdJMy9nNFdGVkhvd2s3Rk5qdUlWdzBDc0dsS05XZldkeG9NV0Y4YkNsVEpoRU9Td3ZkbQprU1NYdllpdzlkVVhDa3kweXgvdzE2WkN4ZXBPUzJsTUFqc3ZjenhWd3dZbUZ4RDBQUEdrbkIwOUdNUjVXNzdPCjVQdFhRMUo2T1pNcmVLdDB0YllOZ25LTHdqSk5GZVFxZzZCR2ZYQVFwUkhNUHpIdHlNV3MxWkg2TTQwZ0FoVEgKQjkwbzJ1QWQwRXpWM1p0YWp3dnBHSmN0UFJvQXNmYWpjTDRqOFU5MUlpTmMyLzRtK3RQZ0lCVUJZT0ZJWDBWbApQVG8yMU1tcWdBSXREeGNJRDZjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFPclFRMXZoMlk0WE5mWC9BWEluNEtuVlArdVIKaW15Y0dQdmJiZTJqYXZOVHRGMGJ5Ui9QdGxNNDlzSmxZWEhwSStyYmZxYzd3SGx5RTdmVFA3TWRseTJFTDVTUwpCQW94d3p6eVUzeFpBTUptbHRGWitWMDZ4Zi94aE1TY2FvTW5EQ0Q2TmdBbmZvMkNmRGxaR2NHeXJNNUVZeDFICkg5dXpNWmxTc3NSQTE4Y1c3UlNZYW9oazhHenZJc2grUitKd1l5bnoxZTBzOXVZYzFEM20xbWl4dFpsY2dGNjAKOW5leFlVQlBqVlIxc1ZLZGxsdmcxclRHZHdTQ3ZaV28vL1NBS0RmWEZHRnFoM3QyWEVzcUNWY3pkWVozMFdpVQpQMGdNbnBzWW8yUmpGbHN6SitoUUVRNlBQei9HZHQ4RlEwODlzTTBtM2ZWdnRMRXc3NVpzczgrRUphdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: openkube-webhook-service
      namespace: openkube-system
      path: /mutate-apps-openKube-com-v1beta1-unitedset
  failurePolicy: Fail
  name: munitedset.kb.io
  rules:
  - apiGroups:
    - apps.openKube.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - unitedsets
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: openkube-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3hNekF5TURBMU4xb1hEVE13TURjeE1UQXlNREExTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEZRCkhlbDd1SW4vVGVGbmFHRVlvOElOQWlZeEFrbmF1UnY2TGhYVXYwV25lRHFONVJ1M0FoRzM5ZlJvSFhzQURRUWIKWWRXRmtjU1FJUGNzWmdJMy9nNFdGVkhvd2s3Rk5qdUlWdzBDc0dsS05XZldkeG9NV0Y4YkNsVEpoRU9Td3ZkbQprU1NYdllpdzlkVVhDa3kweXgvdzE2WkN4ZXBPUzJsTUFqc3ZjenhWd3dZbUZ4RDBQUEdrbkIwOUdNUjVXNzdPCjVQdFhRMUo2T1pNcmVLdDB0YllOZ25LTHdqSk5GZVFxZzZCR2ZYQVFwUkhNUHpIdHlNV3MxWkg2TTQwZ0FoVEgKQjkwbzJ1QWQwRXpWM1p0YWp3dnBHSmN0UFJvQXNmYWpjTDRqOFU5MUlpTmMyLzRtK3RQZ0lCVUJZT0ZJWDBWbApQVG8yMU1tcWdBSXREeGNJRDZjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFPclFRMXZoMlk0WE5mWC9BWEluNEtuVlArdVIKaW15Y0dQdmJiZTJqYXZOVHRGMGJ5Ui9QdGxNNDlzSmxZWEhwSStyYmZxYzd3SGx5RTdmVFA3TWRseTJFTDVTUwpCQW94d3p6eVUzeFpBTUptbHRGWitWMDZ4Zi94aE1TY2FvTW5EQ0Q2TmdBbmZvMkNmRGxaR2NHeXJNNUVZeDFICkg5dXpNWmxTc3NSQTE4Y1c3UlNZYW9oazhHenZJc2grUitKd1l5bnoxZTBzOXVZYzFEM20xbWl4dFpsY2dGNjAKOW5leFlVQlBqVlIxc1ZLZGxsdmcxclRHZHdTQ3ZaV28vL1NBS0RmWEZHRnFoM3QyWEVzcUNWY3pkWVozMFdpVQpQMGdNbnBzWW8yUmpGbHN6SitoUUVRNlBQei9HZHQ4RlEwODlzTTBtM2ZWdnRMRXc3NVpzczgrRUphdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: openkube-webhook-service
      namespace: openkube-system
      path: /validate-apps-openKube-com-v1beta1-unitedset
  failurePolicy: Fail
  name: vunitedset.kb.io
  rules:
  - apiGroups:
    - apps.openKube.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - unitedsets

